--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VISTA_FUTBOL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LALIGA"."VISTA_FUTBOL" ("NOMBRE", "NOMBREJUGADOR", "SALARIO") AS 
  SELECT
  E.NOMBRE,
  J.NOMBREJUGADOR,
  J.SALARIO
  
FROM
  JUGADORES J,
  EQUIPO E 
  
WHERE 
  J.EQUIPO_ID = E.EQUIPO_ID 
  AND J.SALARIO >= 2000;
--------------------------------------------------------
--  DDL for Table AFICION
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AFICION" 
   (	"EQUIPO_ID" NUMBER, 
	"AFICION_ID" NUMBER, 
	"NOMBRE_GUERRA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANTICOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."CANTICOS" 
   (	"CANTICOS_ID" NUMBER, 
	"AFICION_ID" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "LALIGA"."EQUIPO" 
   (	"EQUIPO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"FECHA_FUNDACION" DATE, 
	"ESTADIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."EQUIPO"."NOMBRE" IS 'Denominacion del equipo
';
   COMMENT ON COLUMN "LALIGA"."EQUIPO"."FECHA_FUNDACION" IS 'Fecha
';
--------------------------------------------------------
--  DDL for Table ESTADIO
--------------------------------------------------------

  CREATE TABLE "LALIGA"."ESTADIO" 
   (	"ESTADIO_ID" NUMBER, 
	"LOCALIZACIÓN" VARCHAR2(50 BYTE), 
	"AFORO" NUMBER, 
	"EQUIPO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "LALIGA"."JUGADORES" 
   (	"JUGADORES_ID" VARCHAR2(50 BYTE), 
	"EDAD" NUMBER, 
	"ALTURA" NUMBER, 
	"DORSAL" NUMBER, 
	"EQUIPO_ID" NUMBER, 
	"NOMBREJUGADOR" VARCHAR2(20 BYTE), 
	"SALARIO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEGUIDORES_PELIGROSOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."SEGUIDORES_PELIGROSOS" 
   (	"SEGUIDORES_ID" NUMBER, 
	"DNI" VARCHAR2(20 BYTE), 
	"FECHA_NACIMIENTO" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LALIGA.AFICION
SET DEFINE OFF;
Insert into LALIGA.AFICION (EQUIPO_ID,AFICION_ID,NOMBRE_GUERRA) values ('1','1','MADRIDISTAS');
REM INSERTING into LALIGA.CANTICOS
SET DEFINE OFF;
Insert into LALIGA.CANTICOS (CANTICOS_ID,AFICION_ID) values ('1','1');
Insert into LALIGA.CANTICOS (CANTICOS_ID,AFICION_ID) values ('2','1');
REM INSERTING into LALIGA.EQUIPO
SET DEFINE OFF;
Insert into LALIGA.EQUIPO (EQUIPO_ID,NOMBRE,FECHA_FUNDACION,ESTADIO_ID) values ('1','REALMADRID',to_date('07/06/02','DD/MM/RR'),null);
REM INSERTING into LALIGA.ESTADIO
SET DEFINE OFF;
Insert into LALIGA.ESTADIO (ESTADIO_ID,"LOCALIZACIÓN",AFORO,EQUIPO) values ('1','MADRID','85454',null);
REM INSERTING into LALIGA.JUGADORES
SET DEFINE OFF;
Insert into LALIGA.JUGADORES (JUGADORES_ID,EDAD,ALTURA,DORSAL,EQUIPO_ID,NOMBREJUGADOR,SALARIO) values ('1','25','172','17','1','LUCAS','3000');
Insert into LALIGA.JUGADORES (JUGADORES_ID,EDAD,ALTURA,DORSAL,EQUIPO_ID,NOMBREJUGADOR,SALARIO) values ('2','28','170','12','1','MARCELO','1500');
Insert into LALIGA.JUGADORES (JUGADORES_ID,EDAD,ALTURA,DORSAL,EQUIPO_ID,NOMBREJUGADOR,SALARIO) values ('3','20','180','20','1','ASENSIO','2500');
Insert into LALIGA.JUGADORES (JUGADORES_ID,EDAD,ALTURA,DORSAL,EQUIPO_ID,NOMBREJUGADOR,SALARIO) values ('4','23','185','9','1','MORATA','2600');
REM INSERTING into LALIGA.SEGUIDORES_PELIGROSOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."EQUIPO_PK" ON "LALIGA"."EQUIPO" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AFICION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."AFICION_PK" ON "LALIGA"."AFICION" ("AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CANTICOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."CANTICOS_PK" ON "LALIGA"."CANTICOS" ("CANTICOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SEGUIDORES_PELIGROSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."SEGUIDORES_PELIGROSOS_PK" ON "LALIGA"."SEGUIDORES_PELIGROSOS" ("SEGUIDORES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."ESTADIO_PK" ON "LALIGA"."ESTADIO" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JUGADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."JUGADORES_PK" ON "LALIGA"."JUGADORES" ("JUGADORES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ESTADIO
--------------------------------------------------------

  ALTER TABLE "LALIGA"."ESTADIO" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."ESTADIO" ADD CONSTRAINT "ESTADIO_PK" PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "LALIGA"."EQUIPO" ADD CONSTRAINT "EQUIPO_PK" PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."CANTICOS" MODIFY ("CANTICOS_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."CANTICOS" ADD CONSTRAINT "CANTICOS_PK" PRIMARY KEY ("CANTICOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "LALIGA"."JUGADORES" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."JUGADORES" MODIFY ("JUGADORES_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."JUGADORES" ADD CONSTRAINT "JUGADORES_PK" PRIMARY KEY ("JUGADORES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEGUIDORES_PELIGROSOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."SEGUIDORES_PELIGROSOS" MODIFY ("SEGUIDORES_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."SEGUIDORES_PELIGROSOS" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."SEGUIDORES_PELIGROSOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."SEGUIDORES_PELIGROSOS" ADD CONSTRAINT "SEGUIDORES_PELIGROSOS_PK" PRIMARY KEY ("SEGUIDORES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AFICION" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AFICION" MODIFY ("NOMBRE_GUERRA" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AFICION" ADD CONSTRAINT "AFICION_PK" PRIMARY KEY ("AFICION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AFICION" ADD CONSTRAINT "EQUIPO_FK" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LALIGA"."EQUIPO" ("EQUIPO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."CANTICOS" ADD CONSTRAINT "AFICION_ID" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "LALIGA"."AFICION" ("AFICION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "LALIGA"."EQUIPO" ADD CONSTRAINT "ESTADIO_ID" FOREIGN KEY ("ESTADIO_ID")
	  REFERENCES "LALIGA"."ESTADIO" ("ESTADIO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "LALIGA"."JUGADORES" ADD CONSTRAINT "EQUIPO_ID" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LALIGA"."EQUIPO" ("EQUIPO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEGUIDORES_PELIGROSOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."SEGUIDORES_PELIGROSOS" ADD CONSTRAINT "SEGUIDORES_PELIGROSOS_FK1" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "LALIGA"."AFICION" ("AFICION_ID") ENABLE;
